name: DockerOVPN Dockerfile workflow
on: 
  pull_request: {}
  push:
    branches:
      - master
env:
  AWS_REGION : "us-east-1"
  ECR_REPOSITORY: nimbux911/dockovpn
  VERSION: 2.6.8-config.0.1.0
permissions:
      id-token: write
      contents: read
jobs:
  DockerfileUpload:
    runs-on: ubuntu-22.04
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: rolesession
          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_ADDRESS }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .

          echo "printing current branch name"
          echo ${GITHUB_REF_NAME}

          if [ "${GITHUB_REF_NAME}" = "master" ]
          then
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          fi